name: Get Citation Data


on:

  page_build:

  schedule:

    - cron: '0 8 * * *'


jobs:


  build:


    runs-on: ubuntu-latest



    steps:


      - name: Checkout repository

        uses: actions/checkout@v4




      - name: Install requirements

        run: |

          sudo apt-get update

          sudo apt-get install -y python3-setuptools




      - name: Run Google Scholar crawler

        env:

          GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}


        run: |


          cd ./google_scholar_crawler


          echo "Installing python dependencies..."


          python3 -m pip install -r requirements.txt



          echo "Starting crawler..."



          timeout 300 python3 -u main.py




      - name: Update citation data


        run: |


          cd ./google_scholar_crawler/results



          git init



          git config --local user.name "${GITHUB_ACTOR}"

          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"



          export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"



          git add *.json



          git commit -m "Updated Citation Data"



          git push "${remote_repo}" HEAD:google-scholar-stats --force
